M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date 17.12.2024 (вт) 16:05:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-17T16:05:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X11.61Y44.97
X17.39Y44.97
T2
X7.0Y49.0
X7.0Y2.0
X22.0Y49.0
X22.0Y2.0
M30
